Algoritmo "66-F"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ana Julia
// Data atual  : 08/04/2025
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para numero de 1 ate 199 faca
      se (numero mod 4 = 0) entao
         Escreval(numero)
      fimse
   fimpara

Fimalgoritmo