Algoritmo "1 - Contagem 1 a 10"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ana Julia
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 1
   enquanto numero <= 10 faca
      Escreval(numero)
      numero <- numero + 1
   fimenquanto
Fimalgoritmo